package interfaces;

public class Main {
    /*UNA INTERFAZ ES UNA COLECCION DE METODOS ABSTRACTOS DONDE HAY ATRIBUTOS CONSTANTES, EN ESTA SE PERMITE LA HERENCIA MULTIPLE
    *
    * CUANDO CREAMOS UNA INTERFAZ DEBEMOS CAMBIAR EL CLASS POR INTERFACE
    *
    * CUANDO CREAMOS UN METODO NO DEBEMOS PODER NADA, SE QUEDAN ASI
    *
    * CUANDO VAYAMOS A CONECTAR NO USAMOS EXTEND SI NO IMPLEMENTS
    *
    * TENER EN CUENTA QU TODOS LOS METODOS ABSTRACTOS CREADOS SE DEBEN IMPLEMENTAR DONDE SE LLAME CADA INTERFAZ
    *
    * PARA LLAMAR VARIAS INTEFASES DESPUES DEL IMPLEMENT PONEMOS SUS NOMBRES SEPARADOS POR COMAS*/
}
